var FName="Tanish";
var LName="Jalan";
var FuLLName=FName.concat(LName);
console.log(FuLLName);
var a=10;
var b=5;
var add= a + b;
var sub= a - b;
var mul= a * b;
var div= a / b;
console.log(add);
console.log(sub);
console.log(mul);
console.log(div);